package dao

const (
	OP        = "op"
	COUNT     = "count"
	LIST      = "list"
	ID        = "id"
	OTHER_ID  = "otherId"
	OUR_ID    = "ourId"
	TAG       = "tag"
	QUERY_OK  = "queryOk"
	IS_OK     = "isOk"
	ERR_MSG   = "errMsg"
	NAME      = "name"
	AGE       = "age"
	SEX       = "sex"
	INTRO     = "intro"
	NEW_PED   = "newpwd"
	OLD_PED   = "oldpwd"
	EXIST     = "exist"
	CONTENT   = "content"
	USER_ID   = "user_id"
	FRIEND_ID = "friendId"
	TOKEN     = "token"
	ROLE      = "role"
	AUTH      = "auth"
)
